name: python ci piplines 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name : checkout code 
        uses: actions/checkout@v4

      - name : setup python
        uses : actions/python@v5
        with:
          python-version: '3.11'
      
      - name : Run the script 
        uses: python app.py

      